### ISSUE TITLE
'Jud 2' goes to Revelation 1, not Judges 2.

### ISSUE THREAD

**Issue by daviewales** [mdbergmann/Eloquent#69]
I don't know if this quite counts as a bug. But it may not be quite the expected behaviour!

If you enter 'Jud 2' (or 3, 4, etc) into the reference search bar, it takes you to Revelation 1 (or 2, 3 respectively).
I'm guessing that Jud -> Jude, then it just counts forward 2 chapters, taking us to Revelation 1.

I discovered this while searching for Judges 6 (Jud 6), which took me to Revelation 5.
However, I suspect that it may be less confusing if the logic incorporated the maximum chapter count.

e.g. `min(max_chapters_in_book, given_value)`

Then 'Jud 6' would take one to Jude 1, which should hopefully be a good hint that we need to type 'Judg 6' instead!

**Comment by mdbergmann** [comment]
Hi.

Yeah, I think 'Jud' is short form for 'Jude', where 'Judg' is for 'Judges'.

The logic behind the referencing and chapter counting is actually performed by the [SWORD library](http://crosswire.org/sword/index.jsp) where Eloquent is based on.
So Eloquent is not really involved in this.

I would refer you to SWORD (due to a lack of time) if you want to find out exactly what is the reason behind this behavior.

**Comment by daviewales** [comment]
Ah! Thank you.
